In [39]:
#Importing the required libraries
import pandas as pd
import numpy as np

import statsmodels.stats.api as sms
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import(
    RandomForestRegressor,
    AdaBoostRegressor,
    GradientBoostingRegressor,
    StackingRegressor,
)

#import matplotlib.pyplot as plt

from sklearn.linear_model import Lasso


import warnings
warnings.filterwarnings("ignore")

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [40]:
#Importing the Regression algorithmms from their respective libraries
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,GradientBoostingRegressor,AdaBoostRegressor,ExtraTreesRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor

In [49]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import r2_score,mean_absolute_error

In [42]:
#Reading the dataset
df= pd.read_csv('MobilePhonedata_new2.csv')
df.head()

,Unnamed: 0,Brand,Model,ROM,RAM,OS,Screen size,Dual Sim,Expandable Memory,5G,Fingerprint Sensor,Price
0,0,Huawei,Y5 Prime,16.0,2.0,Android,5.45,1,1,0,1,5000
1,1,Huawei,Y5,16.0,2.0,Android,5.71,1,1,0,1,5000
2,2,Apple,iPhone 4S,16.0,0.5,iOS,3.50,0,0,0,0,5000
3,3,Huawei,Y5,16.0,2.0,Android,5.71,0,0,0,0,5000
4,4,Huawei,Y5,16.0,2.0,Android,5.71,1,0,0,0,5000

<h3>Hyperparameter Tuning: </h3>
<p>1. GridSearchCV</p>
<p>2. RandomizedSearchCV</p>

In [43]:
#Importing GridSearchCV and RandomizedSearchCV
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import uniform as sp_randFloat
from scipy.stats import randint as sp_randInt

In [44]:
df = df.iloc[: , 1:]
X=df.drop("Price", axis=1)
y=df[["Price"]]
df.head()

,Brand,Model,ROM,RAM,OS,Screen size,Dual Sim,Expandable Memory,5G,Fingerprint Sensor,Price
0,Huawei,Y5 Prime,16.0,2.0,Android,5.45,1,1,0,1,5000
1,Huawei,Y5,16.0,2.0,Android,5.71,1,1,0,1,5000
2,Apple,iPhone 4S,16.0,0.5,iOS,3.50,0,0,0,0,5000
3,Huawei,Y5,16.0,2.0,Android,5.71,0,0,0,0,5000
4,Huawei,Y5,16.0,2.0,Android,5.71,1,0,0,0,5000

In [45]:
#Getting X.info()
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40023 entries, 0 to 40022
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Brand               40023 non-null  object
 1   Model               40023 non-null  object
 2   ROM                 40023 non-null  float64
 3   RAM                 40023 non-null  float64
 4   OS                  40023 non-null  object
 5   Screen size         40023 non-null  float64
 6   Dual Sim            40023 non-null  int64
 7   Expandable Memory   40023 non-null  int64
 8   5G                  40023 non-null  int64
 9   Fingerprint Sensor  40023 non-null  int64
dtypes: float64(3), int64(4), object(3)
memory usage: 3.1+ MB

In [46]:
#Price column
y

       Price
0       5000
1       5000
2       5000
3       5000
4       5000
...      ...
40018  50050
40019  57000
40020  60060
40021  40060
40022  62000

[40023 rows x 1 columns]

In [47]:
#split the data into train and test
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,y,test_size=0.05, random_state=32
)

In [48]:

print("X_train: ",np.shape(X_train))
print("X_test:",np.shape(X_test))
print("y_train: ",np.shape(y_train))
print("y_test: ",np.shape(y_test))

X_train:  (38021, 10)
X_test: (2002, 10)
y_train:  (38021, 1)
y_test:  (2002, 1)

In [50]:
step1 = ColumnTransformer(transformers=[('col_tnf',OneHotEncoder(handle_unknown='ignore',sparse=False,drop='first'),[0,1,4])
],remainder='passthrough')

step2 = step1.fit_transform(X_train)
pd.DataFrame(step2).head()

# step3 = step1.fit_transform(y_train)
# pd.DataFrame(step3).head()

,0,1,2,3,4,5,6,7,8,9,...,610,611,612,613,614,615,616,617,618,619
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,64.0,4.0,5.85,0.0,0.0,0.0,1.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,32.0,2.0,4.70,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,128.0,3.0,5.50,0.0,1.0,0.0,1.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,32.0,2.0,4.70,0.0,1.0,0.0,1.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,64.0,2.0,6.53,1.0,1.0,0.0,1.0

<h4>Regressors used for tuning</h4>
<br>
1. Gradient Boost Regressor<br>
2. K-Nearest Neighbor<br>
3. Random Forest Regressor<br>

<h4>Grid Search for GradientBoost</h4>

In [12]:
GBR = GradientBoostingRegressor()
parameters = {'learning_rate': [0.01,0.001],
                  'subsample'    : [0.9,0.5],
                  'n_estimators' : [100,500],
                  'max_depth'    : [4,6]
                 }
grid_GBR = GridSearchCV(estimator=GBR, param_grid = parameters, cv = 2, n_jobs=-1)
grid_GBR.fit(step2, y_train)  

print(" Results from Grid Search " )
print("\n The best estimator across ALL searched params:\n",grid_GBR.best_estimator_)
print("\n The best score across ALL searched params:\n",grid_GBR.best_score_)
print("\n The best parameters across ALL searched params:\n",grid_GBR.best_params_)

 Results from Grid Search

 The best estimator across ALL searched params:
 GradientBoostingRegressor(learning_rate=0.01, max_depth=6, n_estimators=500,
                          subsample=0.9)

 The best score across ALL searched params:
 0.9662071722114665

 The best parameters across ALL searched params:
 {'learning_rate': 0.01, 'max_depth': 6, 'n_estimators': 500, 'subsample': 0.9}

<h4>Random Search for GradientBoost</h4>

In [ ]:
GBR = GradientBoostingRegressor()
parameters = {'learning_rate': sp_randFloat(),
                'subsample'    : sp_randFloat(),
                'n_estimators' : sp_randInt(100, 1000),
                'max_depth'    : sp_randInt(4, 10)
                 }

randm_src = RandomizedSearchCV(estimator=GBR, param_distributions = parameters,
                               cv = 2, n_iter = 10, n_jobs=-1)
randm_src.fit(step2, y_train)

print(" Results from Random Search " )
print("\n The best estimator across ALL searched params:\n", randm_src.best_estimator_)
print("\n The best score across ALL searched params:\n", randm_src.best_score_)
print("\n The best parameters across ALL searched params:\n", randm_src.best_params_)

<h4>Grid Search for KNN</h4>

In [19]:
KNN = KNeighborsRegressor()
parameters = {'n_neighbors': [1,2,3,4,5,6,7,8,9,10,11,12]}
grid_GBR = GridSearchCV(estimator=KNN, param_grid = parameters, cv = 2, n_jobs=-1)
grid_GBR.fit(step2, y_train)    

print(" Results from Grid Search " )
print("\n The best estimator across ALL searched params:\n",grid_GBR.best_estimator_)
print("\n The best score across ALL searched params:\n",grid_GBR.best_score_)
print(grid_GBR.rmse())
print("\n The best parameters across ALL searched params:\n",grid_GBR.best_params_)

 Results from Grid Search

 The best estimator across ALL searched params:
 KNeighborsRegressor(n_neighbors=4)

 The best score across ALL searched params:
 0.9615727394024749

 The best parameters across ALL searched params:
 {'n_neighbors': 4}

<h4>Random Search for KNN</h4>

In [51]:
KNN = KNeighborsRegressor()
parameters = {'n_neighbors': sp_randInt(0,30)}

randm_src = RandomizedSearchCV(estimator=KNN, param_distributions = parameters,
                               cv = 2, n_iter = 10, n_jobs=-1)
randm_src.fit(step2, y_train)

print(" Results from Random Search " )
print("\n The best estimator across ALL searched params:\n", randm_src.best_estimator_)
print("\n The best score across ALL searched params:\n", randm_src.best_score_)
print("\n The best parameters across ALL searched params:\n", randm_src.best_params_)

 Results from Random Search

 The best estimator across ALL searched params:
 KNeighborsRegressor(n_neighbors=4)

 The best score across ALL searched params:
 0.960903863162696

 The best parameters across ALL searched params:
 {'n_neighbors': 4}

<h4>Grid Search for RandomForest Regressor</h4>

In [ ]:
RFR = RandomForestRegressor()
parameters = {'n_estimators': [300,350,400],
              'random_state': [2,3,5],
              'max_samples': [0.2,0.5,0.7],
              'max_features': [0.5,0.75,1.0],
              'max_depth': [10,15,20]
             }
grid_GBR = GridSearchCV(estimator=RFR, param_grid = parameters, cv = 2, n_jobs=-1)
grid_GBR.fit(step2, y_train) 

print(" Results from Grid Search " )
print("\n The best estimator across ALL searched params:\n",grid_GBR.best_estimator_)
print("\n The best score across ALL searched params:\n",grid_GBR.best_score_)
print("\n The best parameters across ALL searched params:\n",grid_GBR.best_params_)

<h4>Random Search for RandomForest Regressor</h4>

In [17]:
RFR = RandomForestRegressor()
parameters = {'n_estimators': sp_randInt(250,500),
              'random_state': sp_randInt(1,10),
              'max_samples': sp_randFloat(),
              'max_features': sp_randFloat(),
              'max_depth': sp_randInt(5,25)
             }

randm_src = RandomizedSearchCV(estimator=RFR, param_distributions = parameters,
                               cv = 2, n_iter = 10, n_jobs=-1)
randm_src.fit(step2, y_train)

print(" Results from Random Search " )
print("\n The best estimator across ALL searched params:\n", randm_src.best_estimator_)
print("\n The best score across ALL searched params:\n", randm_src.best_score_)
print("\n The best parameters across ALL searched params:\n", randm_src.best_params_)

 Results from Random Search

 The best estimator across ALL searched params:
 RandomForestRegressor(max_depth=18, max_features=0.5571267634226393,
                      max_samples=0.9548484610714333, n_estimators=309,
                      random_state=2)

 The best score across ALL searched params:
 0.9698213348464662

 The best parameters across ALL searched params:
 {'max_depth': 18, 'max_features': 0.5571267634226393, 'max_samples': 0.9548484610714333, 'n_estimators': 309, 'random_state': 2}

<h4>Grid Search for Ridge Regressor</h4>

In [14]:
RR = Ridge()
parameters = {'alpha': [0.001,0.005,0.01,0.02,0.04,0.05,0.09,0.1]}

grid_GBR = GridSearchCV(estimator=RR, param_grid = parameters, cv = 2, n_jobs=-1)
grid_GBR.fit(step2, y_train) 

print(" Results from Grid Search " )
print("\n The best estimator across ALL searched params:\n",grid_GBR.best_estimator_)
print("\n The best score across ALL searched params:\n",grid_GBR.best_score_)
print("\n The best parameters across ALL searched params:\n",grid_GBR.best_params_)

 Results from Grid Search

 The best estimator across ALL searched params:
 Ridge(alpha=0.02)

 The best score across ALL searched params:
 0.9713463238861147

 The best parameters across ALL searched params:
 {'alpha': 0.02}

<h4>Random Search for Ridge Regressor</h4>

In [13]:
RR = Ridge()
parameters = {'alpha': sp_randFloat(0.01,0.1)}

randm_src = RandomizedSearchCV(estimator=RR, param_distributions = parameters,
                               cv = 2, n_iter = 10, n_jobs=-1)
randm_src.fit(step2, y_train)

print(" Results from Random Search " )
print("\n The best estimator across ALL searched params:\n", randm_src.best_estimator_)
print("\n The best score across ALL searched params:\n", randm_src.best_score_)
print("\n The best parameters across ALL searched params:\n", randm_src.best_params_)

 Results from Random Search

 The best estimator across ALL searched params:
 Ridge(alpha=0.03233046834708502)

 The best score across ALL searched params:
 0.971346641000015

 The best parameters across ALL searched params:
 {'alpha': 0.03233046834708502}